apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  continers:
  - name: k8s-demo
    image: arjunchari12/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
