apiVersion: v1
kind: Pod
metadata:
  name: javahelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: maven-demo
    image: yasu1234shaik/mavenhelloworld
    ports:
    - name: javaport
      containerPort: 3001
